/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import com.mycompany.crudapp1.Player;
import com.mycompany.crudapp1.PlayersDAOImp;
import com.mycompany.crudapp1.PlayersServiceLayer;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author k2
 */
public class ViewPanel extends javax.swing.JPanel {
    MainFrame main;
    /**
     * Creates new form ViewPanel
     * @param main
     */
    public ViewPanel(MainFrame main) {
        this.main = main;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        allBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataField = new javax.swing.JTextArea();
        byIdBtn = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();

        allBtn.setText("View All");
        allBtn.addActionListener(this::allBtnActionPerformed);

        backBtn.setText("Back");
        backBtn.addActionListener(this::backBtnActionPerformed);

        jLabel1.setText("ID:");

        dataField.setEditable(false);
        dataField.setColumns(20);
        dataField.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        dataField.setRows(5);
        jScrollPane1.setViewportView(dataField);

        byIdBtn.setText("View By ID");
        byIdBtn.addActionListener(this::byIdBtnActionPerformed);

        warningLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningLabel.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(backBtn)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idField, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(byIdBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(allBtn)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(warningLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(warningLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(allBtn)
                    .addComponent(jLabel1)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(byIdBtn))
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void allBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allBtnActionPerformed
        PlayersServiceLayer pService = new PlayersServiceLayer(new PlayersDAOImp());
        String s = "";
        
        try {
            List<Player> players = pService.getAllPlayers();
            for (Player p : players) {
                s += p.getId() + " " + p.getName() + " " + p.getTime_in_sec() + "\n";
            }
            warningLabel.setText("-");
        } catch (Exception e) {
            warningLabel.setText("Error on getting all data.");
        }
        
        dataField.setText(s);
    }//GEN-LAST:event_allBtnActionPerformed

    private void byIdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byIdBtnActionPerformed
        PlayersServiceLayer pService = new PlayersServiceLayer(new PlayersDAOImp());
        try {
            Player p = pService.getPlayerById(idField.getText());
            dataField.setText(p.getId() + " " + p.getName() + " " + p.getTime_in_sec());
            warningLabel.setText("-");
        } catch (Exception e) {
            warningLabel.setText(e.getMessage());
        }
        
        idField.setText("");
    }//GEN-LAST:event_byIdBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        main.showPanel("LANDING");
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton byIdBtn;
    private javax.swing.JTextArea dataField;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
